spring.application.name=ToDoListApplication
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/react-survey-db
spring.datasource.username=admin
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update